// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	app "github.com/ahrtolia/goboot/pkg"
	"github.com/ahrtolia/goboot/pkg/config"
	"github.com/ahrtolia/goboot/pkg/cron"
	"github.com/ahrtolia/goboot/pkg/gin"
	"github.com/ahrtolia/goboot/pkg/gorm"
	"github.com/ahrtolia/goboot/pkg/logger"
	redispkg "github.com/ahrtolia/goboot/pkg/redis"
	"github.com/google/wire"
)

// Injectors from wire.go:

func CreateApp(configFile2 string) (*app.App, error) {
	options := config.NewOptions(configFile2)
	configManager := config.InitConfigManager(options)
	zapLogger, err := logger.NewLogger(configManager)
	if err != nil {
		return nil, err
	}
	option, err := gin.NewOption(configManager)
	if err != nil {
		return nil, err
	}
	server, err := gin.NewServer(zapLogger, configManager, option)
	if err != nil {
		return nil, err
	}
	gormOption, err := gorm.NewOption(configManager)
	if err != nil {
		return nil, err
	}
	db := gorm.New(gormOption)
	cronOption, err := cron.NewOption(configManager)
	if err != nil {
		return nil, err
	}
	scheduler, err := cron.NewScheduler(zapLogger, configManager, cronOption)
	if err != nil {
		return nil, err
	}
	redisOption, err := redispkg.NewOption(configManager)
	if err != nil {
		return nil, err
	}
	redisClient, err := redispkg.NewClient(zapLogger, configManager, redisOption)
	if err != nil {
		return nil, err
	}
	context := app.NewContext(configManager, zapLogger, server, db, scheduler, redisClient)
	loggerStarter := app.NewLoggerStarter(configManager, zapLogger)
	httpStarter := app.NewHTTPStarter(configManager, server)
	gormStarter := app.NewGormStarter(configManager, db)
	cronStarter := app.NewCronStarter(configManager, scheduler)
	redisStarter := app.NewRedisStarter(configManager, redisClient)
	v := app.NewStarters(loggerStarter, httpStarter, gormStarter, cronStarter, redisStarter)
	appApp, err := app.New(configManager, context, v)
	if err != nil {
		return nil, err
	}
	return appApp, nil
}

// wire.go:

var (
	configSet = wire.NewSet(config.ProviderSet, config.NacosProvider)

	loggerSet = wire.NewSet(logger.ProviderSet)

	httpSet = wire.NewSet(gin.ProviderSet)

	dbSet = wire.NewSet(gorm.ProviderSet)

	cronSet = wire.NewSet(cron.ProviderSet)

	redisSet = wire.NewSet(redispkg.ProviderSet)

	appSet = wire.NewSet(app.ProviderSet)

	globalSet = wire.NewSet(
		configSet,
		loggerSet,
		httpSet,
		dbSet,
		cronSet,
		redisSet,
		appSet,
	)
)
